version: "3"
services:
  frontend:
    image: ghcr.io/freegtd/freegtd-frontend:latest
    restart: always
    ports:
      - "9000:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/freegtd/freegtd-backend:latest
    restart: always
    volumes:
      - ./backend/data:/data

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30