version: "3"
services:
  frontend:
    image: ghcr.io/freegtd/freegtd-frontend:v0.0.4
    restart: always

  backend:
    image: ghcr.io/freegtd/freegtd-backend:v0.0.3
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
