version: "3"
services:
  frontend:
    image: ghcr.io/freegtd/freegtd-frontend:latest
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./frontend/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: ghcr.io/freegtd/freegtd-backend:latest
    restart: always
    volumes:
      - ./backend/data:/data
